### ISSUE TITLE
[Suggestion] Verb Watcher

### ISSUE THREAD

**Issue by stefanwalther** [verbose/verb#101]
**Current situation:**
I am using verb quite often in combination with `grip` (https://github.com/joeyespo/grip), just to review my READMEs before uploading.
Currently - after each change - I have to run `verb` in the CLI.

**Proposal:**
It would be extremely helpful to have an option for verb (or `verb-cli` basically) to watch the changes in the following files:

`verb -w` watches the following changes and re-runs `verb`:
- `package.json` - Just in cases you are making changes to the configuration of verb
- `verbfile.js` - In case you change the custom `verbfile.js` file
- `.verb.md` - To watch the structure of the default verb file.
- `./docs/**/*.*` - Watch all changes of .md files, but also any other files in this directory (e.g. images, etc.)

@jonschlinkert, @doowb: What do you think?

**Comment by tunnckoCore** [comment]
I believe you can do this manually currently with `dev/0.9.0`.

**verbfile.js**

```js

var watch = require('base-watch')
var verb = require('verb');
var app = verb().use(watch());

app.watch([
  'package.json',
  'verbfile.js',
  '.verb.md',
  './docs/**/*.*'
], {options: 'to chokidar'})

module.exports = app;
```

docs https://github.com/node-base/base-watch

**Comment by stefanwalther** [comment]
Tried to use this, not working, do you have a working setup based on the latest version of verb?

**Comment by jonschlinkert** [comment]
try https://github.com/jonschlinkert/romanize#building-docs

**Comment by stefanwalther** [comment]
... solved it with a different approach, using [docker-verb](https://github.com/stefanwalther/docker-verb) and nodemon: https://github.com/stefanwalther/docker-verb#watching-doc-changes

... therefore closing this issue/suggestion ...

**Comment by jonschlinkert** [comment]
@stefanwalther that's awesome! 

btw, as a side note, I know I've been saying this forever, but we're very close to merging verb to master and publishing. we're finally working on the finishing touches to some libraries we wanted to finish first.

**Comment by stefanwalther** [comment]
@jonschlinkert That sounds good/perfect and having now the docker image it makes it much easier for me to migrate all projects because I can just update the docker image all my project will just be using ;-)
