### ISSUE TITLE
Dev branch publish recommendations

### ISSUE THREAD

**Issue by phated** [verbose/verb#107]
As discussed earlier, here are my recommendations for handling the `dev` branch of verb:

1. Merge the `dev` branch into master
2. Semver major bump (I like `npm version major -m 'Release: %s'`)
3. Publish to npm with a custom tag (probably `next`) using `npm publish --tag next` - More information at https://docs.npmjs.com/getting-started/using-tags#publishing-with-tags
4. Install into packages or globally with `npm install verb@next`

This should allow you to start shipping the `dev` branch in your projects without messing with others' workflow.

**Comment by jonschlinkert** [comment]
awesome, we'll do this asap. thanks!

**Comment by stefanwalther** [comment]
Any plans to get this done in the near future?
