### ISSUE TITLE
Cannot install verb anymore after changes in 0.8.8

### ISSUE THREAD

**Issue by stefanwalther** [verbose/verb#73]
Hi,

does anybody experience the same issues? After updates for 0.8.8 I cannot install anymore, both fails:

```js
npm install verbose/verb --save-dev
npm install verb --save-dev
```

Error msg:
```bash
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
"verb" "--save-dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\bla-bla-bla\bla-bla-blanpm-debug.log

```

**Comment by jonschlinkert** [comment]
I know exactly what's causing this. I'll get a fix pushed up. sorry about this (once again). I'm trying to the refactor of verb finished so we can get past these issues!

**Comment by doowb** [comment]
@stefanwalther have you tried this again? The error message says that it's most likely related to a network connectivity issue.

**Comment by doowb** [comment]
I've found some missing dependencies and updated `verb` and `verb-cli`. Try updating them globally by doing:

```sh
$ npm cache clear -g && npm i verb-cli verb -g
```

Since you're using a windows machine, let us know if you have different results.

**Comment by jonschlinkert** [comment]
@stefanwalther did @doowb's suggestion work?

**Comment by stefanwalther** [comment]
Sorry for the late response, I am on vacation, will give it a try tonight ...

**Comment by jonschlinkert** [comment]
no rush! we are more concerned with whether or not it's working for you. please take your time

**Comment by stefanwalther** [comment]
Hi @jonschlinkert, I am unfortunately still getting the same error using `npm install verbose\verb --save-dev`

What I haven't done so far is to clear the npm cache, but I still have to publish some projects in the next days and I am afraid of breaking them ;-)
Will test it again in a few days with clearing the npm cache. I should do that, right?

**Comment by adjohnson916** [comment]
@stefanwalther Are you able to install other npm modules from the same system?

**Comment by jonschlinkert** [comment]
> clearing the npm cache. I should do that, right?

yeah, clearing the cache and reinstalling verb-cli and verb is necessary. I clear my cache constantly.

**Comment by stefanwalther** [comment]
You generally install it globally, right?

**Comment by stefanwalther** [comment]
@adjohnson916, yes, all others work fine ...

**Comment by stefanwalther** [comment]
Thx all, works after clearing the cache and re-installing, thx a lot!!!
