### ISSUE TITLE
0.9.0: loading config values

### ISSUE THREAD

**Issue by jonschlinkert** [verbose/verb#79]
Question: should we try to load configuration settings from globally defined plugins AND user config (.e.g. package.json), or just user?

**Background**

In the verb 0.9.0, we're using the [base-config](https://github.com/jonschlinkert/base-config) plugin to automatically load options/settings, plugins, helpers, templates and so on from a user-supplied configuration. 

In particular, if the user defines a `verb` property in package.json, the config plugin maps over that object and takes whatever action we've defined for each property. 

For example, if you defined the following in package.json, we would load `options` onto `verb.options`:

```js
"verb": {
  "options": {
    "foo": true
  }
}
```

@doowb, anyone, thoughts?

**Comment by doowb** [comment]
If we load settings from globally defined plugins, then I think it would be easier to make a plugin that just defines some templates like layouts, docs, includes, etc... Then a user can override those with their local package.json settings. This would provide a convention of where the templates are specified and have them all loaded onto `base`.

If we don't load the settings, then globally defined plugins would have the responsibility of loading the templates on `base` themselves... or loading onto their own `verb` instance if there's a reason for that.

I'd vote for loading configuration settings from globally defined plugins first, then user defined configuration settings could override those.

**Comment by jonschlinkert** [comment]
that sounds like a good way to go.

**Comment by tunnckoCore** [comment]
:+1: same here

- if it matters :)

**Comment by jonschlinkert** [comment]
> if it matters :)

of course it matters! thanks!

**Comment by jonschlinkert** [comment]
closing since this is resolved. generators can load config themselves. verb loads user config
