### ISSUE TITLE
Including entire content of a JavaScript file

### ISSUE THREAD

**Issue by stefanwalther** [verbose/verb#83]
Hi,

is it possible to include the entire content of a JavaScript file (e.g. an example, a recipe, etc.)?

Regards
Stefan

**Comment by jonschlinkert** [comment]
sorry I don't remember seeing this! 

If I understand correctly, you just want to read in a javascript file as a string, correct? if so, with 0.9.0 you can easily do this with a helper or plugin. registering plugins and helpers works the same way as assemble. let me know if this helps or you have questions

**Comment by stefanwalther** [comment]
Solved it with a plugin, thx.

**Comment by jonschlinkert** [comment]
@stefanwalther have you tried out 0.9 yet? or still on older version?
