### ISSUE TITLE
0.9.0: cli: TypeError when using globally stored `tasks: [readme]`

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#86]
As we know currently we can store things globally through `--save`, so i stored some configs

```
verb --save tasks:readme
verb --save layout:empty
verb --save toc:false
```

So, when run just `verb` it simply fails with

```
[TypeError: tasks.split is not a function]
```
very cool :D I'm digging to find from where come from about an hour ;d Maybe composer or even bach, but i can't see such thing lol.

**notice** it's specific, all other is working correctly (for example `verb readme` is as expected), also works if configs are stored locally in package.json on the project.

**~/data-store/verb.json**
```json
{
  "layout": "empty",
  "tasks": [
    "readme"
  ],
  "toc": false
}
```

**Comment by tunnckoCore** [comment]
Oookey, that was cool, found it. lol. 
I can bet problem is coming from here [base-runner/index.js#L212-L219](https://github.com/node-base/base-runner/blob/master/index.js#L212-L219)

**Comment by tunnckoCore** [comment]
closing as per https://github.com/node-base/base-runner/issues/2

**Comment by jonschlinkert** [comment]
awesome, thanks for debugging. we'll get these all streamlined over time, it will get easier
