### ISSUE TITLE
0.9.0: load generators defined in package.json

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#87]
Same way as we do for plugins, if you don't need to pass some options to plugin/generator it can be array like this

```json
"verb": {
  "generators": [
    "verb-readme-generator"
  ]
}
```

But... this `verb.generators` should also be able to accept object where key would be name of the generator, value would be options object passed directly to generator. This will help every generator to have separate options and gives a user more control.

For example, we can pass custom templates (different for includes, badges, or same for all) path in the cwd package.json, before that it also should look for global config from `~/data-store/verb.json`.
Related (https://github.com/verbose/verb-readme-generator/issues/2)

local package.json verb config
```json
"verb": {
  "generators": {
    "verb-readme-generator": {
      "includes": "/home/charlike/.config/verb/includes",
      "layouts": "./docs",
      "badges": "./templates/badges"
    }
  }
}
```

global verb config from `~/data-store/verb.json`

```json
{
  "layout": "empty",
  "generators": {
    "verb-readme-generator": {
      "includes": "./includes",
      "layouts": "/home/charlike/dev/project/docs",
      "badges": "~/.config/verb/badges"
    }
  }
}
```

Above are just examples and shows the things mixed, intentionally. Which makes me think filepaths that will be written in global config always must be resolved to full filepaths.

***

As writing this, I'm waiting fix for the resolving problems (can't load globally installed generator). :)

Cheers,
Charlike!

**Comment by jonschlinkert** [comment]
good ideas! but I have a few questions/thoughts:

Would the generators still be globally installed and invoked? e.g. package.json is just providing options?
Or do you also want to load generators that way? Either should be doable, but the second has a lot more to consider.

**Comment by tunnckoCore** [comment]
> Would the generators still be globally installed and invoked? e.g. package.json is just providing options?

Yes. I think we don't want to force users to install generators per project - it may need/worth do it this way in some case (i don't have any cases in my mind). So yea, they still be globally installed and invoked and they will trying to use 1) options from global config, 2) options from current project package.json.
