### ISSUE TITLE
0.9.0: way to remove default `gulp-format-md` plugin

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#90]
Actually, a way to not include it at all on init time.

**Comment by jonschlinkert** [comment]
it's not included anywhere. you have to include it yourself. are you adding it when doing `--init`?

**Comment by tunnckoCore** [comment]
Mm, yea, my mistake. I'm talking that it is added in anyway to your package.json on `--init`, you don't have a way to "no, i don't want any plugins to be added to verb local config", no way to skip it. Yes, you have a way to not install plugins (because it asks you) and remove the `verb.plugins` array manually.

**Comment by jonschlinkert** [comment]
> remove the verb.plugins array manually.

really? I thought it did `omitEmpty` on the result. Sorry I'll get that fixed

**Comment by jonschlinkert** [comment]
yeah I really had no idea what to make the init questions. open to suggestions

**Comment by jonschlinkert** [comment]
but the fact that we're talking about fixing CLI stuff at least means we're getting  close to releasing 0.9.0!

**Comment by tunnckoCore** [comment]
> but the fact that we're talking about 

Ahaha, yea! I'm proud with you, :laughing: 

> had no idea what to make the init questions

just stop use `verb` at all, use `readme-generator`, hahah, just kidding.

> really? I thought it did omitEmpty on the result. 

I don't know, but i'm feeling that again I wasn't clear enough, sorry.
I'm talking about that there's no way to skip this question and in same time to not have `verb.plugins` on local config, because the question default is `gulp-format-md`.
Maybe the fix and better thing would be the question to not have default value (as currently) at all, and because you specifically want to use it, you have global config for that thing.

**Comment by jonschlinkert** [comment]
> because the question default is gulp-format-md.

got it. I'll fix it. I'd rather not remove the default until it's seamless to use your own defaults

**Comment by tunnckoCore** [comment]
I can agree, but when it comes to CLI it shoudn't be so opinionated.
