### ISSUE TITLE
0.9.0: Adding helpers from `verbfile.js`?

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#94]
That's strange. I tried in a couple of ways that i know that it should work. Also checked how it's done on other libs and generators.

The #91 "problem" push me to try some things and start playing with `toc` options and verb in general. In a result I realize couple of things:

- there's no `toc` template helper - e.g. using `{%= toc() %}`
- you can't pass options for `toc` through `<!-- toc -->`
  + i seen somewhere thing like `<!-- toc('*.md', opts) -->`
  + so i tried `toc('README.md', {filter: fn})`, but not works - the html comment is the same
- can't overwrite toc options? - the easiest way to try that was to add `toc: {footer: 'foo'}` to pkg
- then i tried to add to verbfile (exposing function) some sync helper manually
  + tried using it in verbfile `{%= foo('bar') %}` and failed with `foo is not defined`
  + tried `verb.helper('foo', require('helper-date'))` - again fails with `foo is not defined`
  + tried to create task, add above to it and execute it - not works.
  + tried using `verb.extendWith` and put some tasks/helpers in it - not works.

So, couple of problems

- there's a need to expose `helper-toc` to template, b/c currently it only can be from `<!-- -->`
- there's no way to add filter (in general any) options to toc, neither through config and template
- there's some problem adding helpers

edit: Tried everything that I can think for.
edit2: One of the tried ways:

```js
'use strict'

module.exports = function generator(verb) {
  verb.extendWith(function (app) {
    // console.log('app', app)
    app.task('foobar', function (cb) {
      console.log('actual')
      app.helper('foo', function () {
        console.log('helper')
        return 123
      })
      cb()
    })
    app.build('foobar', function (err, res) {
      console.log('build', err, res)
    })
  })
}
```
Fails with `foo is not defined`

```
[charlike@voltaire async-simple-iterator]$ verb
[20:00:54] using verbfile ~/dev/__play/async-simple-iterator/verbfile.js
[20:00:54] starting default generator
[20:00:54] starting default:foobar task
actual
[20:00:54] finished default:foobar task 2ms
[20:00:54] finished default generator 14ms
build undefined undefined
[20:00:54] starting readme generator
[20:00:54] starting readme:readme task
[20:00:54] starting readme generator
[20:00:55] finished readme generator 50ms
ReferenceError: foo is not defined
    at eval (engine.templateSources[1]:16:11)
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/engine-cache/index.js:201:17
    at Object.wrappedRender [as render] (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/engine-cache/index.js:256:7)
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/templates/lib/plugins/render.js:291:16
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/templates/lib/plugins/routes.js:133:7
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:576:15
    at next (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:161:14)
    at /home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:183:18
    at Function.matchLayer (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:264:3)
    at next (/home/charlike/.nvm/versions/node/v5.8.0/lib/node_modules/verb/node_modules/en-route/lib/index.js:164:10)
ENV: <Generator default [string] /home/charlike/dev/__play/async-simple-iterator/verbfile.js>

```

The another again fails with above output. It was simply:

```js
'use strict'

module.exports = function generator(verb) {
  verb.helper('foo', require('helper-date'))
}
```

**Comment by jonschlinkert** [comment]
Try doing `{%= toc %}`,  it might work.  But in my experience TOC's don't work the way you want. I learned the long and hard way. That said, if you only use a single file in your docs (no includes, or layouts at all), and none of the headings will change based on context, rendering or content, the ignore my previous comment. 

If you use a helper, then you need to wait until all of the files are rendered to create the TOC, or at least until the file that has the TOC helper is rendered, which means all the files usually. and  you will also almost always want to filter things out of the TOC afterwards. which means something different in every project.

IMO it's better to do with middleware, and it's not as trivial as it might seem. 

> helper-toc

That's only if the use `.inject` which is really for the CLI and the middleware use case. If you want to figure out a way to do it with a helper, you can see how I do it in the readme generator. It adds a `toc` to a file first, then it inlines that wherever a `<!-- toc -->` comment is. 

what are you really trying to accomplish?

**Comment by jonschlinkert** [comment]
> module.exports = function generator(verb) {
>   verb.helper('foo', require('helper-date'))
> }

Yeah looks correct. You're not running that verbfile.js. It needs to at least invoked to expose the helper on the instance. If you want to run the other generator, just use `.extendWith` or to namespace it use `.register`

**Comment by tunnckoCore** [comment]
> what are you really trying to accomplish?

Initially, I wanted to filter out last heading from the readme. But that's not the only problem - you can't change toc footer if you want - that's the the smallest thing that proof that something is wrong somewhere.

> You're not running that verbfile.js.

Wait, what? It is executed and even some things works as expected.

**Comment by tunnckoCore** [comment]
> Yeah looks correct.

:laughing: yea, but not works. lol

**Comment by jonschlinkert** [comment]
Was that last example pseudo code then? 

I can't get online, as soon as my connection is back up I'll take a look

**Comment by tunnckoCore** [comment]
> pseudo code then?

No, all examples are tried and ran locally.

**Comment by jonschlinkert** [comment]
But you said this "isn't working", right?

```js
module.exports = function generator(verb) {
  console.log(verb)
}
```

what is running that helper? what is calling `.render`?

**Comment by tunnckoCore** [comment]
> But you said this "isn't working", right?

Actually, yea, you're right for that example - "it works", shows verb instance, it's okey. lol

> also you mentioned .extendWith, but I don't see that.

The first example of first post uses it.

Nevermind, we are going in wrong direction. All that issue is about is that when you try to add helper from `verbfile.js` and run `verb` it throws error that this helper is not defined. Simply:

**.verb.md**

```md
Some {%= toUpperCase('content') } here
```

**verbfile.js**

```js
module.exports = function (verb) {
  verb.helper('toUpperCase', function (str) {
    return str.toUpperCase()
  })
}
```

**error**

```
ReferenceError: toUpperCase is not defined
```

**Comment by jonschlinkert** [comment]
> and run verb it throws error that this helper is not defined. Simply:

honestly this is something that has made me want to pull my hair out a few times. I totally understand how frustrating this can be, you're being very patient

anyway, from what i can see, the error you're getting makes sense. If there is something rendering the templates, it has already loaded all of the helpers onto the context by the time it gets to that one. you need to make sure that render is called after the helpers are loaded.

**Comment by jonschlinkert** [comment]
@doowb and I are talking about this. It might be something else but I don't think it's a "bug". regardless it's a usability issue. 

I think I have an idea for how to make sure users don't need to think about this... need to think for a sec

**Comment by jonschlinkert** [comment]
also, one more thing I want to emphasize. Just because you are seeing the instance doesn't mean it's the correct instance. You need to do `.extendWith('verb-readme-generator')` or setup the logic you need for loading/rendering templates. what's probably happening is that your just seeing the helper being registered on the instance of your local generator, but you're actually running the readme generator, which is a different instance.

**Comment by tunnckoCore** [comment]
With this example

```js
module.exports = function (verb) {
  console.log(verb)
}
```

i just said that the verbfile is executed correctly when you said _"You're not running that verbfile.js"_. Other things in you last comment is clear, I understand them.

> anyway, from what i can see, the error you're getting makes sense. It might be something else but I don't think it's a "bug".

Yea, I was thinking the same thing.

> you need to make sure that render is called after the helpers are loaded.

How? And why users should do this thing, when verbfile is meant to be used to extend the things and workflow with plugins, tasks and adding more data?

> I think I have an idea for how to make sure users don't need to think about this...

:+1:

**Comment by jonschlinkert** [comment]
try running this (if `verb.tasks = ['readme']` is defined in package.json verb config, just do `verb`, otherwise do `verb readme`)

```js
module.exports = function(app) {
  app.extendWith('verb-readme-generator');
  app.helper('toUpperCase', function (str) {
    return str.toUpperCase()
  });
  app.task('default', ['readme']);
};
```

**Comment by jonschlinkert** [comment]
what we're doing in that example is extending our local generator with the tasks and context of `verb-readme-generator`.

just thinking out loud about making this more magical. 

- A generator can't "run" anything if it doesn't have tasks. 
- You **can** extend a generator with tasks helpers and anything else from other generators 
- to run the `readme` generator, you can directly do `verb readme` to run `verb-readme-generator`, or, if you do `.extendWith` you can just run `verb` since your local generator will be extended with the readme generator. 

We _could_ automatically extend the local generator with whatever generator you run from the command line, but IMO that will end up causing more issues because it hides what's happening, and it's so easy to write one line of code to do this in a generator...

**Comment by jonschlinkert** [comment]
Okay, here is a more detailed example. make sure you pay close attention to the `new App` variable names and how the instances are passed (it's pseudo-code, but it explains what's going on)

Here are our two generators, `readme` and the one in your local project, `verbfile.js`.

```js
// --verb-readme-generator--
function genertorReadme(app) {
  app.task('readme', function() {
    return app.src('.verb.md')
      .pipe(app.dest(function(file) {
        file.basename = 'README.md';
        return file.base;
      }))
  });
  app.task('default', ['readme']);
};

// --my-project/generator.js--
function generatorLocal(app) {
  // custom stuff
  app.helper('upperCase', function() {});
}
```

Here is (in pseudo-code) what happens when you run:

```sh
$ verb readme
```

Both generators get their own instance.

```js
// --verb-readme-generator--
var readme = new App();
genertorReadme(readme);

// --my-project/generator.js--
var local = new App();
generatorLocal(local);

// so you're doing this
local.helper('upperCase', function() {});

// but you need to do this
readme.helper('upperCase', function() {});
```

So we need to do this (again, in pseudo-code):

```js
var readme = new App();
genertorReadme(readme);

// --my-project/generator.js--
generatorLocal(readme);
```

Which is accomplished by doing this:

```js
local.extendWith('verb-readme-generator');
```

**Comment by tunnckoCore** [comment]
> try running this

:+1: works.

> Which is accomplished by doing this:

That's clear.

But what about this scenario: what about if user not use any generator? He just want to use `verbfile.js` to add some more data to his template or add more helpers and he didn't installed any local/global generator?
Also I mentioned that I tried to add helper: 1) inside `app.extendWith` (custom generator in verbfile), 2) inside `app.task()` and running that task with `app.build`, 3) inside `app.task` which is inside `app.extendWith`. Neither of this ways not worked.

**Comment by jonschlinkert** [comment]
> He just want to use verbfile.js to add some more data to his template or add more helpers and he didn't installed any local/global generator? E.g. we just have globally installed verb and nothing more.

Then you would create the logic you need. just like a gulpfile, or assemblefile, or gruntfile. like:

```js
module.exports = function(app) {
  app.task('readme', function() {
    return app.src('.verb.md')
      .pipe(app.dest(function(file) {
        file.basename = 'README.md';
        return file.base;
      }))
  });
  app.task('default', ['readme']);
};
```

but the huge advantage here is that you can define multiple "generators" like this and combine them using `.extendWith` (btw, that will just be `.use` when I push up the next changes. `.extendWith` will work too.). 

One more thing is that it's possible you're not aware of all the things that generator can do yet (and I'm clouding my understanding of what you want with that knowledge). so let's just keep talking through it

**Comment by jonschlinkert** [comment]
>  we just have globally installed verb and nothing more.

to emphasize, that is the same as asking: "what will gulp do with my files if I just install it globally and run `gulp`".

Generators are just a way of doing advanced task composition.

**Comment by tunnckoCore** [comment]
> to emphasize, that is the same as asking

actually, not so - not exactly, lol.

**verbfile.js**
```js
module.exports = function(app) {
  app.task('readme', function() {
    app.helper('toUpperCase', function(str) {
      return str.toUpperCase();
    });
    return app.src('.verb.md')
      .pipe(app.dest(function(file) {
        file.basename = 'README.md';
        return file.base;
      }))
  });
}
```

**package.json**

```json
{
  "name": "foo-bar",
  "version": "0.0.0",
  "description": "Playing with verb.",
  "main": "index.js",
  "verb": {
    "run": true,
    "toc": false,
    "layout": "empty",
    "lint": {
      "reflinks": true
    }
  }
}
```

**.verb.md**

```markdown
# Welcome player
Some {%= toUpperCase('foo bar') %} content
```

Running 
```
[charlike@voltaire foo-bar]$ verb
[02:32:41] using verbfile ~/dev/__play/foo-bar/verbfile.js
[02:32:41] finished ✔
```
Do nothing, that's okey, that's clear.

running

```
[charlike@voltaire foo-bar]$ verb readme
[02:32:53] using verbfile ~/dev/__play/foo-bar/verbfile.js
[02:32:53] starting default generator
[02:32:53] starting default:readme task
[02:32:54] finished default:readme task 432ms
[02:32:54] finished default generator 445ms
[02:32:54] finished ✔
[charlike@voltaire foo-bar]$
```
adds `README.md` file, but with same content as `.verb.md` (not rendered).

```md
# Welcome player
Some {%= toUpperCase('foo bar') %} content
```

So how to add/use helpers if we don't want too much staff?

I just want to point that I don't need anything of this currently, it not stopping my job - my using verb and it works out of the box for me without the need to add verbfile.js (and I won't). I'm just trying to learn more verb and to understand what and how happens.

**Comment by jonschlinkert** [comment]
@tunnckoCore you're saying "I know, I know", but I think you're making all of your assumptions based on what verb-readme-generator does. 

Generators are just plugins.

- If you want to add helpers to your generator, then create a generator and add helpers to it.
- If you want to add helpers to **another generator**, then you need to add the helpers to the other generator's instance. You are adding helpers to your generator's instance and expecting the other generator to magically reach out and grab them. 

> what about if user not use any generator? He just want to use verbfile.js to add some more data to his template or add more helpers and he didn't installed any local/global generator

What if I wanted to fly? How would that work? Why would anyone expect to be able to do this:

```js
function foo() {}
```

Then run `verb`, and expect that function to generate files?

But you can do this:

```js
module.exports = function(app) {
  app.use('any-other-generator-that-does-something-you-want');
}
```

I don't see how it can get any simpler. We could shorten `app` to `a` and `.use to `.u`?

**Comment by jonschlinkert** [comment]
@tunnckoCore are you thinking we should have built-in generators? Like make `verb-readme-generator` built-in?

**Comment by tunnckoCore** [comment]
No, no, no. I'll say again - wrong direction.

> If you want to add helpers to your generator, then create a generator and add helpers to it.

Isn't `verbifile.js` a generator itself? So why scenario from my previous comment didn't work?

> What if I wanted to fly? How would that work? Why would anyone expect to be able to do this:

So verb can't work (can't do anything) without generators? So why then there are so built-in helpers in tons of deps? Haha, that's not true, I'm sure.

> are you thinking we should have built-in generators?

Totally no. We have built-in helpers and they are enough.

So big discussion and I still can't realize how to add helper to verb using verbfile and not using any generator, because verbfile itself is generator to `generate`.

> but I think you're making all of your assumptions based on what verb-readme-generator does.

Nope.

**Comment by jonschlinkert** [comment]
> Isn't verbifile.js a generator itself? So why scenario from my previous comment didn't work?

yes. it's exactly like a gulpfile that can be registered with a name and installed globally. Or an `assemblefile.js`. Try creating an assemblefile.js, add a helper to it then try to run it without setting up any tasks or loading templates.

> We have built-in helpers and they are enough.

No, we don't have any built-in helpers. I don't know where you got that idea. verb-readme-generator, which is just a plugin for verb, loads its own helpers. **Everything** that is related to generating a readme comes from `verb-readme-generator` <= hence the name lol

> So why then there are so built-in helpers in tons of deps?

Where? Verb has like 3 or 4 deps. I think you're confusing something fundamental here. 

> verbfile itself is generator to generate.

Verb is a generic documentation build system that runs plugins, just like gulp, but with a render cycle and special features that help with building docs. There are **zero built-in helpers or generators**. 

Generate is the class that provides the CLI/runner system to verb, allowing verb to resolve globally installed generators (verbfiles that can be used as plugins). There are no built-in helpers, collections, or generators in generate either.

**Comment by jonschlinkert** [comment]
one more thing.

> So why then there are so built-in helpers in tons of deps? Haha, that's not true, I'm sure.

You do this a lot it seems. completely underestimate what's involved in pulling this off. 

Creating a helper is extremely basic and easy. It's just a function, right? 

```js
function lower(str) {
  return str.toLowerCase();
}
```

Registering a helper is easy too

```js
app.helper('lower', lower);
```

Ensuring that the helper is loaded onto the context, bound to a custom helper-context that exposes the app, options, view being rendered, and _render context_, then ensuring that the helper is registered with **any node.js template engine**, consistently and with the same API is not trivial.

That's just for starters. 

Then we have a render cycle that includes middleware stages, instance plugins, pipeline plugins, and everything works (not for you right now because you're trying to do things that shouldn't work). 

And that, still, is just for starters.

So of course, the underlying libraries have the dependencies necessary for this to work. You are the one who is supposed to add helpers and templates and generators and plugins to make this all work. 

But for generate and verb, those modules will be installed globally and IMHO it's an acceptable trade-off for what you get in return. I wouldn't even mind installing verb with every project - who cares?

You have mentioned "all of these dependencies" on more than one occasion, then you create issues with edge cases that we would need to add even more dependencies so support. Right? Meaning you don't think about the fact that you are only one user, and for trying to make the experience work for as many users as possible is what adds dependencies a lot of the time.

Last, `verb-readme-generator` is just **one generator**. It's the first one I published. It will probable be broken into several smaller ones. Again, generators are like gulpfiles, if you want to create smaller, single responsibility generators for your own projects, that would be ideal.

**Comment by tunnckoCore** [comment]
Nevermind. I don't want to continue this discussion. You're describing like for idiot. And yes, you are right that I'm wrong for some parts of my previous comment. Nevermind, I'm not okey last months - something happening in me. I don't know what happening, but I'm confused in general, I have strong need to rest, maybe in another country. Nevermind.

The general question: How to add helper using verbfile without using any generators, without verb-readme-generator - raw verb? Is it possible? And if not, why? Why, when the verbfile is just a generator.

And in final, for your last comment: I'm not trying to do anything special. I just can't realize why simply `app.helper(name, fn)` added to verbfile (generator-style verb file) not works (without adding and invoking verb-readme-generator)?

Good night.

**Comment by jonschlinkert** [comment]
> You're describing like for idiot.

I'm really sorry if it sounded that way, I definitely don't see you that way, neither does @doowb. we're both always impressed with how much you figure out without any docs. on lots of different projects. (also keep in mind that others read these comments. Readers will get confused and just walk away. so I try to spell things out so that people can understand if they're interested).

You always are really helpful with our projects, don't be so hard on yourself. If you're super stressed out, just get some rest! We'll be around when you get back.

> How to add helper using verbfile without using any generators, without verb-readme-generator - raw verb? Is it possible? And if not, why? Why, when the verbfile is just a generator.

Okay, now I think I understand exactly where you're coming from. You are assuming that verb **should** have these things built-in, but it doesn't. You can't understand everything about a project by looking at its code. We need to explain what verb "is".

give me a little while to put an overview together. I think it will be useful for everyone.

**Comment by jonschlinkert** [comment]
Question @tunnckoCore  and @doowb: when a user runs  `verb` **and** a `verbfile.js` exists in the user's cwd **and** the user wants to run a generator other than `verbfile.js`, do you think it makes sense to automatically do `.extendWith` to add the other generator to the generator instance created for `verbfile.js`? If we do, this might result in something like what (I think) @tunnckoCore is expecting. However, I think it could also cause problems, if the user doesn't know what's happening.

**Comment by tunnckoCore** [comment]
> the user wants to run a generator other than verbfile.js

what means "other generator" here? and how he would run it, and why? he just runs verb which runs verbfile (if exist).

Hmm, I don't think so. But can you give example?

**Comment by jonschlinkert** [comment]
`verbfile.js` is a generator, just like `verb-readme-generator`.  If you didn't know that then it sounds like this is where the confusion is.

> just runs verb which runs verbfile (if exist).

Right, if you just run `verb`, it will run `verbfile.js`. If you run `verb readme` it will **NOT** run the generator in your project (`verbfile.js`), it will run the `readme` generator. You're saying you want both to run, correct?

**Comment by jonschlinkert** [comment]
So, to clarify, every verb generator is essentially a `verbfile.js` that exports a function. When a generator is installed globally or published, we usually rename `verbfile.js` to `index.js` or `generator.js` so that it makes more sense as a moduel and the project can still have it's own `verbfile.js` for its own documentation if needed.

**Comment by tunnckoCore** [comment]
> this is where the confusion is.

Yes I know, I mention it a couple of times in above comments.

> You're saying you want both to run, correct?

Actually, no, lol. Don't want anything. When re-read the thread today, I realized that my "problem" is cleaned - meaning clarified by https://github.com/verbose/verb/issues/94#issuecomment-200582924. Realized that you can add helper to verb if there's no generator (meaning in case doing `.extendWith('verb-readme-generator')`), which make sense, helpers are template things, so they need render cycle.

**Comment by jonschlinkert** [comment]
> Yes I know, I mention it a couple of times in above comments.

Your help with these early issues is really valuable. The most important thing for me to get out of these issues is "what can we do to make verb easier to understand and use for the next dev?". I'm trying to do docs right now, it would help if you could just summarized what it was that you were confused on before, and what we can do to make it more clear.

**Comment by tunnckoCore** [comment]
Actually, it's not hard to understand and wasn't so confusing. I just didn't think it. But yea docs that clarifies the cycles and stages would be great. You did it one time in some issue - if I remember it was somewhere around in `base-namespace` or `base-debug`, where you shown the graphic.

It absolutely make sense to fail with reference error that helper not exist in template, when it don't runs the render cycle, and even it does not have template by default.

**Comment by jonschlinkert** [comment]
@tunnckoCore do you remember where I added those images with examples of how plugins work? I can't remember what it was about or I would give more detail... I can't find them

**Comment by tunnckoCore** [comment]
Haha, yea I'll try to find them and ping

**Comment by tunnckoCore** [comment]
Strongly believe it was in some PR comments, hm

**Comment by tunnckoCore** [comment]
@jonschlinkert I'm damn awesome :D The comment was collapsed.
https://github.com/node-base/base-debug/pull/3#discussion_r54457216

**Comment by jonschlinkert** [comment]
lol thanks!
